[tool.poetry]
name = "tca"
version = "1.0.2"
description = ""
authors = ["noprobelm <noprobelm@protonmail.com>"]
readme = "README.md"
include = ["data/"]
packages = [ {include = "terminal_cellular_automaton"} ]

[tool.poetry.dependencies]
python = "^3.11"
rich = "^13.7.0"
requests = "^2.31.0"
textual = "^0.46.0"

[tool.poetry.group.test.dependencies]
ward = "^0.68.0b0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
'tca-cli' = 'terminal_cellular_automaton.__main__:main'
'tca' = 'terminal_cellular_automaton.app:main'
