[tool.poetry]
name = "tca"
version = "0.1.0"
description = ""
authors = ["noprobelm <noprobelm@protonmail.com>"]
readme = "README.md"
include = ["examples/"]
packages = [ {include = "terminal_cellular_automaton"} ]

[tool.poetry.dependencies]
python = "^3.11"
rich = "^13.7.0"
requests = "^2.31.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
'tca' = 'terminal_cellular_automaton.__main__:main'
